### ISSUE TITLE
uninitialized constant ActionController::UrlWriter::URI

### ISSUE THREAD

**Issue by jherdman** [relevance/cap_gun#6]
"uninitialized constant ActionController::UrlWriter::URI" occurs after upgrading our Rails application to 2.3.9.

Backtrace:

<pre>/Users/james/.rvm/gems/ruby-1.8.7-p299/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:466:in `load_missing_constant': uninitialized constant ActionController::UrlWriter::URI (NameError)
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:106:in `const_missing'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/actionpack-2.3.9/lib/action_controller/url_rewriter.rb:96
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/actionmailer-2.3.9/lib/
action_mailer/base.rb:250
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/cap_gun-0.2.4/lib/cap_gun.rb:47
        from /Users/james/.rvm/rubies/ruby-1.8.7-p299/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /Users/james/.rvm/rubies/ruby-1.8.7-p299/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:152:in `require'
        from ././config/../engines/liboly/config/deploy.rb:1:in `load'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:172:in `load_from_file'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:89:in `load'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:86:in `load'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:86:in `each'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:86:in `load'
        from ./config/deploy.rb:3:in `load'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:172:in `load_from_file'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:89:in `load'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:86:in `load'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:86:in `each'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:86:in `load'
        from Capfile:3:in `load' 
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:172:in `load_from_file'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:89:in `load'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:86:in `load'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:86:in `each'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/configuration/loading.rb:86:in `load'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/cli/execute.rb:65:in `load_recipes'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/cli/execute.rb:65:in `each'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/cli/execute.rb:65:in `load_recipes'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/cli/execute.rb:31:in `execute!'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/lib/capistrano/cli/execute.rb:14:in `execute'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/gems/capistrano-2.5.19/bin/cap:4
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/bin/cap:19:in `load'
        from /Users/james/.rvm/gems/ruby-1.8.7-p299/bin/cap:19</pre>

**Comment by jherdman** [comment]
Problem is in Rails. See https://rails.lighthouseapp.com/projects/8994-ruby-on-rails/tickets/5555-actionmailer-239-should-now-require-uri
