### ISSUE TITLE
`deployment_notification': undefined method `content_type'

### ISSUE THREAD

**Issue by gflarity** [relevance/cap_gun#8]
I just did a gem install cap_gun and got the following. Looks like ActionMailer::Base has changed and dependencies weren't pinned?

/Users/gflarity/.rvm/gems/ruby-1.8.7-p352@deploy/gems/cap_gun-0.2.4/lib/cap_gun.rb:65:in `deployment_notification': undefined method`content_type' for #CapGun::Mailer:0x1022957e0 (NoMethodError)
        from /Users/gflarity/.rvm/gems/ruby-1.8.7-p352@deploy/gems/actionpack-3.2.2/lib/abstract_controller/base.rb:167:in `send_action'

**Comment by gflarity** [comment]
I was able to get this working by creating a gemset and hand picking the following gems:
actionmailer (3.1.4)
actionpack (3.1.4)
activemodel (3.1.4)
activesupport (3.1.4)

Now I get following which points to a way forward:

DEPRECATION WARNING: content_type(value) is deprecated. Please pass :content_type as hash key to mail() instead. (called from load at /Users/gflarity/.rvm/gems/ruby-1.8.7-p352@deploy/bin/cap:19)
DEPRECATION WARNING: from(value) is deprecated. Please pass :from as hash key to mail() instead. (called from load at /Users/gflarity/.rvm/gems/ruby-1.8.7-p352@deploy/bin/cap:19)
DEPRECATION WARNING: recipients(value) is deprecated. Please pass :to as hash key to mail() instead. (called from load at /Users/gflarity/.rvm/gems/ruby-1.8.7-p352@deploy/bin/cap:19)
DEPRECATION WARNING: subject(value) is deprecated. Please pass :subject as hash key to mail() instead. (called from load at /Users/gflarity/.rvm/gems/ruby-1.8.7-p352@deploy/bin/cap:19)
DEPRECATION WARNING: body(value) is deprecated. Please pass :body as hash key to mail() instead. (called from load at /Users/gflarity/.rvm/gems/ruby-1.8.7-p352@deploy/bin/cap:19)
DEPRECATION WARNING: charset() is deprecated and will be removed in future versions. (called from load at /Users/gflarity/.rvm/gems/ruby-1.8.7-p352@deploy/bin/cap:19)

**Comment by aryanet** [comment]
I have the same issue.

**Comment by rsanheim** [comment]
Patches appreciated :)  I'm not using cap-gun day to day anymore, so not sure how much maintenance this will get.

**Comment by chicohernando** [comment]
I just looked into cap_gun tonight for the first time and it looks very promising.  However, I am having this same issue and I was wondering if any of you have found/created a solution?
